# Generated by Django 5.2 on 2025-04-29 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_orgprofile_descripcion_alter_orgprofile_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuentes', to='api.orgprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('fuente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.fuente')),
                ('descripcion', models.TextField()),
            ],
            bases=('api.fuente',),
        ),
        migrations.CreateModel(
            name='RepositorioSistema',
            fields=[
                ('fuente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.fuente')),
                ('descripcion', models.TextField()),
            ],
            bases=('api.fuente',),
        ),
        migrations.CreateModel(
            name='SistemaInformacion',
            fields=[
                ('fuente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.fuente')),
                ('descripcion', models.TextField()),
                ('repositorio', models.ManyToManyField(blank=True, related_name='repositoriosdelsistema', to='api.repositoriosistema')),
            ],
            bases=('api.fuente',),
        ),
        migrations.CreateModel(
            name='ProcesoNegocio',
            fields=[
                ('fuente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.fuente')),
                ('descripcion', models.TextField()),
                ('sistema', models.ManyToManyField(blank=True, related_name='sistemasdelproceso', to='api.sistemainformacion')),
            ],
            bases=('api.fuente',),
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('fuente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.fuente')),
                ('descripcion_rol', models.TextField()),
                ('procesos', models.ManyToManyField(blank=True, related_name='procesosdelstakeholder', to='api.procesonegocio')),
            ],
            bases=('api.fuente',),
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('fuente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.fuente')),
                ('descripcion', models.TextField()),
                ('procesos', models.ManyToManyField(blank=True, related_name='procesosdeldepartamento', to='api.procesonegocio')),
                ('stakeholder', models.ManyToManyField(blank=True, related_name='stakeholdersdeldepartamento', to='api.stakeholder')),
            ],
            bases=('api.fuente',),
        ),
    ]
