# Generated by Django 5.2 on 2025-05-02 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fuente_control_repositoriosistema_sistemainformacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('descripcion_fuente', models.TextField()),
                ('departamentos', models.ManyToManyField(to='api.departamento')),
                ('fuente_confirmacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataproblems_fuente2', to='api.fuente')),
                ('fuente_identificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataproblems_fuente1', to='api.fuente')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.orgprofile')),
                ('procesos_negocio', models.ManyToManyField(to='api.procesonegocio')),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stakeholder')),
            ],
        ),
    ]
