# Generated by Django 5.2 on 2025-05-06 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_dataproblem'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='control',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='fuente',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='procesonegocio',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='repositoriosistema',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='sistemainformacion',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='stakeholder',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='fuente',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
    ]
