# Generated by Django 5.2 on 2025-05-06 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_control_options_alter_departamento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='control',
            options={},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fuente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='procesonegocio',
            options={},
        ),
        migrations.AlterModelOptions(
            name='repositoriosistema',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sistemainformacion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stakeholder',
            options={},
        ),
        migrations.RemoveField(
            model_name='fuente',
            name='polymorphic_ctype',
        ),
    ]
