# Generated by Django 5.2 on 2025-05-08 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_control_options_alter_departamento_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataproblem',
            name='fuente_identificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataproblems_fuente1', to='api.fuente'),
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='api.orgprofile')),
            ],
        ),
        migrations.AddField(
            model_name='dataproblem',
            name='Grupo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataproblems_grupos', to='api.grupos'),
        ),
        migrations.CreateModel(
            name='TecnicaAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('es_publica', models.BooleanField(default=False)),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tecnicas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dataproblem',
            name='tecnica_confirmacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataproblems_tecnica2', to='api.tecnicaanalisis'),
        ),
        migrations.AddField(
            model_name='dataproblem',
            name='tecnica_identificacion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='dataproblems_tecnica', to='api.tecnicaanalisis'),
            preserve_default=False,
        ),
    ]
