# Generated by Django 5.2 on 2025-05-08 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_dataproblem_fuente_identificacion_grupos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataproblem',
            name='Grupo',
        ),
        migrations.RemoveField(
            model_name='tecnicaanalisis',
            name='propietario',
        ),
        migrations.RemoveField(
            model_name='dataproblem',
            name='tecnica_confirmacion',
        ),
        migrations.RemoveField(
            model_name='dataproblem',
            name='tecnica_identificacion',
        ),
        migrations.AlterField(
            model_name='dataproblem',
            name='fuente_identificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataproblems_fuente1', to='api.fuente'),
        ),
        migrations.DeleteModel(
            name='Grupos',
        ),
        migrations.DeleteModel(
            name='TecnicaAnalisis',
        ),
    ]
