# Generated by Django 5.2 on 2025-05-08 13:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_dataproblem_fuente_identificacion_grupo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TecnicaAnalisis',
            new_name='TecnicaIdentificacion',
        ),
    ]
