# Generated by Django 5.2.1 on 2025-05-18 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_tecnicaanalisis_tecnicaidentificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DataStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='tecnicaidentificacion',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tecnicas_identificacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HerramientadeAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('es_publica', models.BooleanField(default=False)),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='herramientas_analisis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalisisDataProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causa_raiz', models.TextField()),
                ('data_problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analisis', to='api.dataproblem')),
                ('data_qualities', models.ManyToManyField(blank=True, related_name='analisis_dataproblems', to='api.dataquality')),
                ('data_stages', models.ManyToManyField(blank=True, related_name='analisis_dataproblems', to='api.datastage')),
                ('herramientas', models.ManyToManyField(blank=True, related_name='analisis_dataproblems', to='api.herramientadeanalisis')),
            ],
        ),
    ]
