# Generated by Django 5.2.1 on 2025-09-24 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_dataquality_datastage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='api.orgprofile')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='api.stakeholder')),
            ],
        ),
    ]
