# Generated by Django 5.2.1 on 2025-09-25 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionDataProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.DateField(auto_now_add=True)),
                ('nota', models.IntegerField()),
                ('data_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion', to='api.dataproblem')),
                ('evaluador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones', to='api.person')),
            ],
        ),
    ]
