# Generated by Django 5.2.1 on 2025-11-27 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_evaluaciondataproblem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agg_func', models.CharField(max_length=50)),
                ('matrix', models.JSONField(blank=True, null=True)),
                ('results', models.JSONField(blank=True, null=True)),
                ('promedios', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificacion', to='api.dataproblem')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificacion', to='api.orgprofile')),
                ('roles', models.ManyToManyField(related_name='Clasificadores', to='api.stakeholder')),
            ],
            options={
                'unique_together': {('data_problem', 'organizacion')},
            },
        ),
    ]
