# Generated by Django 5.2.1 on 2025-11-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_clasificacionresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clasificacionresult',
            options={'verbose_name': 'Clasificación', 'verbose_name_plural': 'Clasificaciones'},
        ),
        migrations.AlterUniqueTogether(
            name='clasificacionresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='clasificacionresult',
            name='data_problems',
            field=models.ManyToManyField(related_name='clasificaciones', to='api.dataproblem'),
        ),
        migrations.AlterField(
            model_name='clasificacionresult',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='Clasificadores', to='api.stakeholder'),
        ),
        migrations.RemoveField(
            model_name='clasificacionresult',
            name='data_problem',
        ),
    ]
